source:
    endpoint:
        auth_url: http://localhost:5000/v2.0
        username: admin
        password: e1e40a6094d8d076193d
        tenant_name: admin
destination:
    endpoint:
        auth_url: http://172.18.184.36:5000/v2.0
        username: admin
        password: passwd
        tenant_name: admin
plan:
    # all, used, specific
    tenants: all
    images: all
