source:
    endpoint:
        auth_url: http://172.18.184.65:5000/v2.0
        username: admin
        password: passwd
        tenant_name: admin
    identity:
        connection: mysql+mysqlconnector://root:passwd@172.18.184.65/keystone
destination:
    endpoint:
        auth_url: http://172.18.184.36:5000/v2.0
        username: admin
        password: passwd
        tenant_name: admin
    identity:
        connection: mysql+mysqlconnector://root:passwd@172.18.184.36/keystone
