DEBUG: false
SERVER_NAME: 127.0.0.1:5000
BIND_HOST: 127.0.0.1:5000
CLOUD_DRIVER: pumphouse.fake.Cloud
IDENTITY_DRIVER: pumphouse.fake.Identity
CLOUD_SERVICE: pumphouse.fake.Service
CLOUDS_RESET: true
CLOUDS:
    source:
        endpoint:
            auth_url:    http://127.0.0.1:5000/v2.0
            username:    admin
            password:    nomoresecrete
            tenant_name: admin
        identity:
            connection:  mysql+mysqlconnector://root:root@127.0.0.1/keystone
        fake:
            delays: true
            num_hypervisors: 6
        populate:
            num_servers: 3
            num_tenants: 3
        urls:
            horizon:        http://10.0.0.1/
    destination:
        endpoint:
            auth_url: http://127.0.0.1:5000/v2.0
            username: admin
            password: secrete
            tenant_name: admin
        identity:
            connection: mysql+mysqlconnector://keystone:keystone@127.0.0.1/keystone
        urls:
            horizon:        http://horizon.endpoint.com/
            mos:            http://127.0.0.1:8000/
        fake:
            delays: true
            num_hypervisors: 4
