source:
  -
    name:       good_old_openstack
    auth_url:   http://10.0.0.1:5000/v2.0/
    username:   admin
    password:   admin
    tenant:     admin
    token:      UUID
target:
  -
    name:       mira-os-1
    auth_url:   http://api.endpoint.com:5000/v2.0/
    fuel_url:   http://127.0.0.1:8000/api/
    username:   admin
    password:   admin
    tenant:     admin
    token:      UUID
