source:
  endpoint:
    auth_url:       http://10.0.0.1:5000/v2.0/
    username:       admin
    password:       admin
    tenant_name:    admin
  identity:
    connection:     mysql+mysqlconnector://root:pass@10.0.0.1:3607/keystone
destination:
  endpoint:
    auth_url:       http://api.endpoint.com:5000/v2.0/
    username:       admin
    password:       admin
    tenant_name:    admin
  identity:
    connection:     mysql+mysqlconnector://root:pass@127.0.0.1:3607/keystone
